### ISSUE TITLE
Synoptic: Fix refresh needed on togglButtons and on visibility/control tabs

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/synoptic#13]
There is an issue with the current system that requires users to either refresh or hover on certain widgets on Synoptic. This can be fixed by writing the showEvent.

**Comment by jdrese** [comment]
This one is done Miquel. Give it a try. In general I think I would like to redo those tabs fully (biped, visibility, control_list...)

For example for the control_list and the visibility tabs I find that we have 2 unnecessary files. the UI file and the widget file because we can make this simple UI directly in the widget file itself integrating the functionalities in it. I think it will simplify the structure in there and make it more flexible because now knowing how you can use those tabs and make them your own is a little bit trickier because of some discordant things. control_list is getting the rig controls from the SET from the mgear api itself and the visibility tab is getting the information from a property set on the UI file which makes things scattered. 

I propose the following. The picker is the only one really needed the UI file. I would keep that tab the same but for the control_list and visibility and others I fully write them without the need of the UI file and make an accessible variable in the file so that people set the rig info on it. This will make easier for people to copy the TAB into another folder (been read by the Synoptic env variable) and they can customize those tab tools more easily.

I was thinking as well to add a new biped picker but using the new class that supports QSS. Is that okay?

**Comment by miquelcampos** [comment]
Hi @jdrese  I have tested the changes and works great! Thanks!

For the other changes proposed, it sounds good for me. 

I will close this ticket and the hotfix 1 project tomorrow, so I can tag and make another release. is it OK for you?

**Comment by miquelcampos** [comment]
@jdrese  I am sorry but I have forget to add the changes to the release :( my bad. I move the ticket to 3.1

**Comment by jdrese** [comment]
No problems Miquel. I am still advancing on several things at the same time for mGear but this week and next I'll be off radar because of shows running at work.
